### PR TITLE
Improve README and --help for --new-file-check-interval

### PR DESCRIPTION
**Pull request by troy**
h/t @thiagofigueiro for identifying that this option was not well documented

### CODE REVIEW

**Comment by leonsodhi** [comment]
This is definitely how I'd like things to work, but it's not true today because:

* the minimum interval is [10 seconds](https://github.com/papertrail/remote_syslog2/blob/e6140078b79c74297f334b4b3d72d588b23c46db/config_manager.go#L24), so you can only go higher with `--new-file-check-interval`
* the interval is parsed as a string and thus you specify the units you want to use. Both `--new-file-check-interval=10s` & `--new-file-check-interval=10000ms` are valid

The default value is 10 seconds, though, so we could update the usage.

**Comment by snorecone** [comment]
@troy I went ahead and merged in the configuration changes from master, and this should now work how @leonsodhi would like things to work (by accepting integers for seconds only). I could make it backward compatible by accepting duration strings like `10s`, but that has never been documented, so let me know what y'all think.

**Comment by leonsodhi** [comment]
> I could make it backward compatible by accepting duration strings like 10s, but that has never been documented, so let me know what y'all think.

That makes complete sense to me, although looking at the second comment in [#31](https://github.com/papertrail/remote_syslog2/pull/31) I now wonder whether I had/have all the facts.

@eric I'm thinking we should close PR [#31](https://github.com/papertrail/remote_syslog2/pull/31) unmerged and only allow integers for the `--new-file-check-interval` duration for the reasons @snorecone mentioned, but am I missing anything?

**Comment by troy** [comment]
Added @snorecone and @leonsodhi to assignees on this.

**Comment by troy** [comment]
The string value made it in to the [advanced example](https://github.com/papertrail/remote_syslog2/pull/140#issuecomment-249292799), so people may have used it and we should support both strings and integers.

**Comment by snorecone** [comment]
Strings and integers will be supported in the config files, so I'm calling this good to merge.

**Pull request merged**
