### PR TITLE
Added include_patterns

### PR DESCRIPTION
**Pull request by zulla**

### CODE REVIEW

**Comment by troy** [comment]
Thanks for your time here, @zulia. Could you help me understand a couple things?

* what led you to want this? That is, what was the real-world situation where you wanted to do this?
* what is the default behavior without either include or exclude patterns specified?
* how are the expected cases covered by tests? They aren't part of this PR, just wondering what cases you're expecting to cover.

Thanks!

**Comment by zulla** [comment]
It's useful for a fine-grained selection of log entries, ignoring Facilities/Loglevels. Getting too involved with /etc/asl.conf or /etc/syslog.conf (OSX) costs lots of time in a day-to-day DevOps environment, and you never quite know what you're going to get out of Loglevel Info/Debug.

The default behavior is No-Crash. Which tests are you thinking about?

**Comment by troy** [comment]
Thanks for trying to comment, @zulla. To clarify, the situation I'm looking for is a real-world one; that is, what actual situation led you to want this? The mechanics of how it works makes sense, but I'm trying to understand what this is a great solution to :)

Regarding tests, it seems like at least 3 test-worthy situations are created by this code:

* that all log messages are sent when no include filter is defined
* some basic coverage of the matching; that is, the typical case
* what happens when include and exclude conflict

I'm not sure what "The default behavior is No-Crash" means. It might be that I've been burned too many times by my own code, code that I thought was stable, to think any code I write can live without tests :)

**Comment by zulla** [comment]
This is exhausting. Plz close. Kthxbye

**Comment by troy** [comment]
Okay. I'm sorry that the requirements feel onerous. Merging code without coverage or an explanation what situations it's meant to be a great solution for doesn't serve other users.

**Pull request closed without merging**
