### PR TITLE
Read new log files from the beginning

### PR DESCRIPTION
**Pull request by Bowbaq**
This adds a new flag / config option to read newly detected files from the beginning (instead of the current offset). Files detected on startup are still read from the current offset.

One possible edge case: if log rotations creates new files that match the glob, then they would be sent in their entirety again. This can presumably be worked around by altering the rotating config.

@leonsodhi

### CODE REVIEW

**Comment by troy** [comment]
@Bowbaq could you take a look a https://github.com/papertrail/remote_syslog2/pull/87? I think this may duplicate its functionality. Please see what you think. Based on your conclusions, feel free to close this, describe the differences between this PR and #87, and/or contribute to that PR.

**Comment by Bowbaq** [comment]
@troy it's inspired by #87, but there are a couple differences:
- it doesn't rewind on the files detected at startup. this gets rid of the restart problem
- it's current with master

Leon & I have discussed this somewhat extensively over email. It solves my current problem, which is that using docker on elasticbeanstalk, I was missing the first few lines of log for each new container.

**Comment by troy** [comment]
Thanks, @Bowbaq, that makes total sense. @leonsodhi brought me up to speed. I'll leave this open pending his and your discussions.

**Comment by snorecone** [comment]
This was resolved in #174

**Pull request closed without merging**
