### PR TITLE
Show that facility and severity can be set

### PR DESCRIPTION
**Pull request by armchairlinguist**

### CODE REVIEW

**Comment by leonsodhi** [comment]
Oh man, I'm dumb. Sorry :disappointed:. You were totally right and it actually is `warn`! Brb, gonna go sit in the corner and hang my head in shame

**Comment by armchairlinguist** [comment]
Heh so it is - https://github.com/papertrail/remote_syslog2/blob/b191cae17b5e036d5b850cc687d525323e8d6a72/syslog/priorities.go#L30 (which I guess means we're slightly inconsistent with syslog there, but internally consistent :).

**Comment by mjulian** [comment]
Should we also update the README with all possible values for `severity` and `facility`?

**Comment by armchairlinguist** [comment]
Updating the README seems worthwhile - might take a little more time, though, so I'll go ahead and merge this so we at least have an example, and then see about that. :)

**Pull request merged**
