### PR TITLE
Docker example - Boilerplate

### PR DESCRIPTION
**Pull request by gabrielhesposito**
My hope is that this image can be throughly documented  so remote_syslog2 (**rs2**) can have a docker image for contributors to build on.
tested user
`    1 rs2        0:00 remote_syslog -D`
tested output
`2017-07-19 23:52:07 INFO  remote_syslog.go:55 Connecting to logs.papertrailapp.com:514 over tls`
build instructions
`docker build --build-arg VERSION=v0.19  -t rs2  .`
run (in background, _docker ps_ to confirm)
`docker run --name rs2 -d rs2`
**TODO: Documentation**
This baseplate should have documentation that only corresponds to the docker CLI, very basic starting/stop/removing  containers, confirming that logs send correctly + simple exampling, passing ENV variables to container to manipulate remote_syslog2 cli

### CODE REVIEW

**Comment by gabrielhesposito** [comment]
Should I create document in this PR, or create a new fork ?

**Comment by snorecone** [comment]
Hi @gabrielhesposito,

Thanks for the example! Documentation in this PR would be fine, no need for another one. Can you outline your motivations for this, and how you envision it being used?

**Comment by gabrielhesposito** [comment]
So my motivation for the Dockerfile meaning... a proper use-case for remote_syslog2+docker, why and when it should be shipped with docker- maybe a docker network command to help troubleshoot connection issues...ok ill add documentation into the root README.md on this PR

**Comment by gabrielhesposito** [comment]
@snorecone  too many commits in this PR...besides that I am happy with the example and the documentation

**Pull request closed without merging**
