### PR TITLE
Add a README.md file to the examples/ directory

### PR DESCRIPTION
**Pull request by inxilpro**
This is a very simple readme file for the examples/ directory

### CODE REVIEW

**Comment by inxilpro** [comment]
Depends on #60

**Comment by troy** [comment]
@inxilpro great content. Was there a specific reason you put it in a separate readme? I could ser an argument for putting it in the main one.

**Comment by inxilpro** [comment]
I just figured that made the most sense, as the content is about the examples. It makes sense either way, though.

**Comment by troy** [comment]
Seems reasonable to me. Up for changing the footer in [this](https://github.com/papertrail/remote_syslog2#auto-starting-at-boot) main readme section to link here instead? Your copy/wording has been really thoughtfully done :)

**Comment by inxilpro** [comment]
Done.

**Comment by troy** [comment]
Heck yeah, thanks @inxilpro. Merging.

**Pull request merged**
