### PR TITLE
Remove duplicate init files, in favor of newer version

### PR DESCRIPTION
**Pull request by u2mejc**
Just cleaning up to remove confusion and reduce dev-power to maintain, they were no longer in sync.

### CODE REVIEW

**Comment by u2mejc** [comment]
Hi @leonsodhi, just wanted to bump. This pr should make package management easier moving forward and keep the init files in sync for users installing by hand vs apt-get/rpm. Let me know if you'd like me to amend anything.

**Comment by troy** [comment]
We'll review and merge these when time allows.

**Comment by u2mejc** [comment]
Awesome, thank you @troy !

**Comment by leonsodhi** [comment]
@u2mejc thanks for trying to keep things tidy :-) In this case, the separate init scripts is intentional. The reasoning there is that the packages install r_s2 to a fixed location with a set binary name, and the init script can take advantage of that to more accurately determine if r_s2 is still running.

The init script in the examples dir is for the majority of folks using the tar.gz archives (the packages are still in beta), where anything is possible.

Sorry about the lack of specifics here. It's been a while since I Iast looked at this stuff so this is all quite hazy!

**Pull request closed without merging**
